### ISSUE TITLE
Update the examples README.md

### ISSUE THREAD

**Issue by pbirkhol-ni** [ni/measurementlink-labview#154]
# Bug Report

There is a README.md file in the Example Measurements folder that only applies to the LDO example. Not only is it outdated, but its location indicates that the README is for all examples, which in reality it is for one of the several examples. 

## Possible Solution

We should move the README to the LDO example and update it. We should also consider adding a README to the other examples (if necessary).

[AB#2271371](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2271371)

**Comment by dixonjoel** [comment]
@pbirkhol-ni we've got the root readme and a readme for the cancellable example. Your current PR has a readme and is updating the root one. In addition, I think you'll be deleting the other LDO measurements. So can we just close this issue?
