### ISSUE TITLE
Measurements that error won't response to the client

### ISSUE THREAD

**Issue by pbirkhol-ni** [ni/measurementlink-labview#155]
# Bug Report

If you run a measurement that errors, the error will not get passed back to the client. Instead, nothing will get passed to the client and the call will appear to be hung.

## Repro or Code Sample

None of the examples currently display this error. This is an issue with a relatively new VI (Invoke Measure Logic.vi)

## Expected Behavior

When a measurement errors, a gRPC status should be sent back to the client.

## Current Behavior

No response is sent to the client

## Possible Solution

Properly handle errors in Invoke Measure Logic.vi. Currently, if there is an error, the call to Set Measurement Service Measure Response.vi effectively gets skipped because it doesn't run upon incoming error. We should consider sending the status back upon incoming error.

[AB#2272710](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2272710)

**Comment by aepete** [comment]
Fixed by #156
