### ISSUE TITLE
Add validation to ensure fields within Config, Results, UI have unique names

### ISSUE THREAD

**Issue by aepete** [ni/measurementlink-labview#158]
# Bug Report

Issue was originally raised in #120 by @jasonmreding, though it does not appear that this concern was addressed by the follow-on work item as was intended:

> I think LV services currently have the same problem as Python as identified in this PR (https://ni.visualstudio.com/DevCentral/_git/ASW/pullrequest/401536). I think we should also add validation that all the top level controls in the configurations and outputs have unique names. If it's not convenient to add as part of this PR, it's fine to do in a follow up. However, it seemed timely so I thought I would mention it.

Here is how the InstrumentStudio UI responds to this circumstance:
![image](https://user-images.githubusercontent.com/88401200/213740726-a9c073c8-0901-4094-8610-33099f1537df.png)

Additionally, I've observed that users can get a failure in InstrumentStudio if their UI VI has a label conflict, regardless of whether their Config or Results contain a conflict.  This is acceptable, but optionally / preferably, we could cause for such circumstance to fail "earlier", via validation code under `Run Service.vi`:
![image](https://user-images.githubusercontent.com/88401200/213736236-9ba5c530-cc8c-4a20-9a25-0fba3cf5f679.png)

## Repro or Code Sample

Create two fields of the same name within Config (or two fields within Results) of a G Measurement.

## Expected Behavior

`Run Service.vi` fails gracefully, on account of the provided Config, Results, and/or UI not being representative of a runnable measurement.

## Current Behavior

InstrumentStudio does a decent job of reporting errors for the cases, as shown above.

## Possible Solution

Add validation logic -- presumably alongside the validation we do in `Validate Configuration Metadata.vi` which ensures the names of Config & Results fields are unique.

Additionally, we could also verify that the corresponding labels on respective UI VI(s) match.  (This type of UI validation could also, say, warn a user if their UI VI was missing a control or indicator that's represented within the Config or Results.)

## Your Environment

* Reproduces with MeasurementLink LV Support 0.12.0

[AB#2274777](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2274777)

**Comment by dixonjoel** [comment]
We're not concerned with this additional validation.
