### ISSUE TITLE
Need introduce where to find/download these .vip file

### ISSUE THREAD

**Issue by LawsonGu** [ni/measurementlink-labview#172]
In readme, there is an instruction
`Download and install the MeasurementLink Support for LabVIEW packages in the following order.
ni_lib_labview_grpc_library-x.x.x.x.vip - Required
ni_lib_labview_grpc_servicer-x.x.x.x.vip - Required
ni_measurementlink_service-x.x.x.x.vip - Required
ni_measurementlink_generator-x.x.x.x.vip - Required`

If i was not guess wrong, I think the latest 2 vip files download from [here](https://github.com/ni/grpc-labview/releases/tag/v1.0.0.1)
And the first 2 vip files need build manually from vipb files in [here](https://github.com/ni/measurementlink-labview/tree/main/Source/Build%20Specs)

[AB#2296009](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2296009)

**Comment by aepete** [comment]
All the necessary vip files can be found under "Assets" in the latest release of measurementlink-labview; the current version at time of writing is [version 0.12.2](https://github.com/ni/measurementlink-labview/releases/tag/v0.12.2).

**Comment by LawsonGu** [comment]
Can install those 4 vip files. Close this ticket.
