### ISSUE TITLE
Could not open sfp file in DCPower example

### ISSUE THREAD

**Issue by LawsonGu** [ni/measurementlink-labview#174]
When I was trying to run the [DCPower example](https://github.com/ni/measurementlink-labview/tree/main/Source/Example%20Measurements/NI-DCPower%20Source%20DC%20Voltage), I open the NIDCPowerSourceDCVoltage.instudioproj and then double click run the sfp file. Something stop me. 
![image](https://user-images.githubusercontent.com/101655210/218400196-67b78563-a85e-4487-af6f-8c6429608dcc.png)

My InstrumentStudio version and setting of plugin
![image](https://user-images.githubusercontent.com/101655210/218400422-3f4f15c6-12c0-4336-913c-165ff481b481.png)
![image](https://user-images.githubusercontent.com/101655210/218400483-2bd44f2c-2c71-47f6-ba6b-03f26776e542.png)

[AB#2297496](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2297496)

**Comment by pbirkhol-ni** [comment]
@LawsonGu, did you install MeasurementLink 23.0? That is required to use this example.

**Comment by LawsonGu** [comment]
> @LawsonGu, did you install MeasurementLink 23.0? That is required to use this example.

Yes, download from argo
![image](https://user-images.githubusercontent.com/101655210/218610090-35839a3f-fe5b-415e-9642-6a95d6ef2f9b.png)
