### ISSUE TITLE
Update repo readme with updated strings and screenshots

### ISSUE THREAD

**Issue by rfriedma** [ni/measurementlink-labview#176]
## User Story
The Plugin Generator menu text and screenshots of projects/block diagrams are out of date since our last refactor. Let's get them updated for accuracy.

[AB#2302314](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2302314)

**Comment by dixonjoel** [comment]
#177
