### ISSUE TITLE
Enums do not get the default value from the Measurement Configuration.ctl in InstrumentStudio

### ISSUE THREAD

**Issue by dixonjoel** [ni/measurementlink-labview#231]
# Bug Report

When you create a panel with a LabVIEW UI in InstrumentStudio, the controls on the panel are supposed to initially get the default values from the Measurement Configuration.ctl. This works for most controls, but does not work for enums.

## Repro or Code Sample

Here's a screenshot showing the Measurement Configuration.ctl, the Measurement UI.vi, and the InstrumentStudio panel.

![image](https://github.com/ni/measurementlink-labview/assets/38357562/544268f9-dd43-403d-85c3-293aa3167ac8)

## Expected Behavior

The enum should initially get the value from Measurement Configuration.ctl.

## Current Behavior

The enum uses the default value from Measurement UI.vi instead.

## Possible Solution

We have code that goes through and applies default values from Measurement Configuration.ctl. My guess is that code doesn't have the correct case for enums to apply them.

## Context

This would mean the measurement engineer could be using the wrong default values when testing.

## Your Environment

Windows 11
InstrumentStudio and MeasurementLink 23.5d752
LabVIEW packages: 1.1.0.2

* OS & Device: [e.g. macOS, Windows, Linux] on [Mac, PC]
* `ni-measurement-service` version [e.g. 0.12.3]
* MeasurementLink version [e.g. 23.0.0d123]
* Python version [e.g. 3.9]

[AB#2434956](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2434956)

**Comment by pbirkhol-ni** [comment]
@dixonjoel I cannot reproduce this issue. I looked at the code and it is just calling a `Variant to Data` node. There is no reason that shouldn't work with enums and my testing suggests that it does.
