### ISSUE TITLE
InstrumentStudio displays a blank panel with no errors when `Measurement UI.vi` is broken w/missing dependencies

### ISSUE THREAD

**Issue by bkeryan** [ni/measurementlink-labview#239]
# Bug Report

When `Measurement UI.vi` cannot load due to missing dependencies, InstrumentStudio displays a blank panel and does not display any error messages. Also, it displays a dialog in the top left corner of the screen for a split second, probably a LV searching for VI dialog.

## Repro or Code Sample

Build an EXE for `Keysight 34401A DMM Measurement`. It is currently broken because it doesn't re-export `Keysight 34401A Function.ctl`.

## Expected Behavior

Displays an error.

## Current Behavior

Displays a blank panel with no errors.
![image](https://github.com/ni/measurementlink-labview/assets/17914399/e53ea266-55c4-4728-b7bf-f09a64554569)

## Workaround

Look at `%TEMP%\InstrumentStudio_BrokenVILog_*` for error logs.

## Possible Solution

`Measurement UI - Open & Run.vi` is missing an error wire.

## Context

Trying to test `Keysight 34401A DMM Measurement` with static registration.

## Your Environment

* OS & Device: Windows
* `ni-measurement-service` version: 1.1.0.3
* MeasurementLink version: 23.5
* LabVIEW version: 2020 SP1

[AB#2459119](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2459119)

**Comment by dixonjoel** [comment]
Validated with 23.8d253 installer of MeasurementLink.
