### ISSUE TITLE
Support PPL LabVIEW UIs

### ISSUE THREAD

**Issue by pbirkhol-ni** [ni/measurementlink-labview#245]
## Problem to Solve

Some LabVIEW UIs will need to use a source distribution or PPL in order to be loaded by InstrumentStudio. While this use case is supported in development, it doesn't work well for building an exe or deploying an application. We should add support for building and deploying PPL UIs.

## Proposed Solution
The Post-Build Action.vi handles copying measurement UI VIs to the build output directory. We should modify it to handle PPLs. 

[AB#2466421](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2466421)

**Comment by bkeryan** [comment]
> The Post-Build Action.vi handles copying measurement UI VIs to the build output directory. We should modify it to handle PPLs.

Or allow including dependencies. See https://github.com/ni/measurementlink-labview/issues/240#issuecomment-1646085903
