### ISSUE TITLE
Occasionally facing "Keep waiting for Plugin Shutdown" when we close the Instrument Studio 

### ISSUE THREAD

**Issue by Vasantha-Kumar-J** [ni/measurementlink-labview#27]
When we try to close the Instrument Studio, we are occasionally facing the warning as shown below
![image](https://user-images.githubusercontent.com/28588382/153743187-7c1f0dda-afd3-4ecc-8a8c-1cc884cee145.png)

[AB#2270678](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2270678)

**Comment by dixonjoel** [comment]
We haven't seen this for a while.
