### ISSUE TITLE
Openning project with no driver installed, then install, does not clear the error of no driver until specific VI's are reopen.

### ISSUE THREAD

**Issue by gpachecoNI** [ni/measurementlink-labview#350]
# Bug Report

Opening the project with no drivers installed in your machine will throw an error of "The NI-DMM driver is not installed". The user will then install the driver and would expect that the next time the VI is run the error to go away but it doesn't. 
Seems that the type specialization structure is under the _Initialize MeasurmentLink Session.vi_ and the _Close MeasurmentLink Session.vi_ wont get fix until someone opens the vi's. 

## Repro or Code Sample

1.- Open any of the new examples on a machine with no drivers.  _NI-FGEN Standard Function_ _NI-SCOPE Acquire Waveform_
2,- Run the example and get the expected error _"The NI-xxx driver is not installed"_
3.- Install the expected driver
4.- Re-run the example 

You will be getting the same error. The workaround is to open the VI's that have a type specialization structure. 

## Expected Behavior

The error should have been clear. 

## Current Behavior

It is impossible to remove the error of  "Driver is not installed" until you open the VI's that have a type specialization structure. 

## Possible Solution

N/A

## Context

N/A

## Your Environment

No drivers when starting adding them later.

[AB#2557116](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2557116)

**Comment by jonathanmendez** [comment]
Another workaround is to force-compile the `Measurement Logic.vi` hierarchy (ctrl-shift click on the run arrow).
