### ISSUE TITLE
Provide the Measurement UI template as a Labview template VI. 

### ISSUE THREAD

**Issue by subash-suresh** [ni/measurementlink-labview#40]
Currently, if a user just wanted to create a LabVIEW UI for use with his measurement, he might have to create a new LabVIEW project and then get the UI template file from there. This workflow could be improved by providing the Labview UI template as a LabVIEW template VI so that the user will be able to create measurements as shown below,
![961dc87a-a569-4f19-9ff8-d728c86be0f3](https://user-images.githubusercontent.com/98541596/160801430-49f0a286-572e-42e5-80d9-8eb3842a3b63.jpg)
![8e85b444-a09f-46f1-877e-4c6975e95507](https://user-images.githubusercontent.com/98541596/160801484-54156e69-aa20-4023-a50d-2fc5e09d69d5.jpg)

[AB#2270662](https://dev.azure.com/ni/DevCentral/_workitems/edit/2270662)

**Comment by dixonjoel** [comment]
Template VI for a Measurement UI was added with #251
