### ISSUE TITLE
LV services return the raw error source over the wire, which is not formatted for display

### ISSUE THREAD

**Issue by bkeryan** [ni/measurementlink-labview#453]
# Bug Report

LV-based services return the LV error source field over the wire. This is not quite a developer-facing error message:
- It may be missing the actual static error description, because some drivers (like DAQmx and VISA) expect LabVIEW to fill this in.
- It may contain untranslated XML elements like `<ERR>`, `<APPEND>`, and `<B>...</B>`.
- The call stack is at the beginning of the error and may be quite large.

We should use the `General Error Handler` VI to turn the error cluster into a human-readable string.

## Repro or Code Sample

Run examples without setting up hardware or simulated devices.

## Expected Behavior

The error dialog is readable, shows the error description, and  doesn't display untranslated XML element tags.

## Current Behavior

For MI, the error description is present, but there are no newlines between the call stack and the error description. Instead, there is an `<ERR>` tag.
![image](https://github.com/ni/measurementlink-labview/assets/17914399/f052fbe8-70c8-4b76-af5e-b183d878f5be)

For VISA, the error description is missing entirely. There is no <ERR> tag, so I think VISA relies on LabVIEW to look up the static error description.
![image](https://github.com/ni/measurementlink-labview/assets/17914399/1aa26961-9ad4-42f2-b5ae-50af14f49a7f)

For DAQmx (not pictured), the error dialog will display `<APPEND>` and the static error description will be missing. It will only display the dynamic error description.

## Possible Solution

Change `MeasurementLink Measurement Server\IMeasurement Service\Invoke Measure Logic.vi` to use `General Error Handler`.

Before:
![image](https://github.com/ni/measurementlink-labview/assets/17914399/1dfc1faa-ffb6-4c11-8247-ebd7764cf9b5)

After:
![image](https://github.com/ni/measurementlink-labview/assets/17914399/b952d585-0ff7-44dc-8f61-807e82dca4a5)

MI after:
![image](https://github.com/ni/measurementlink-labview/assets/17914399/f39f09ce-4e4c-47c9-b1c8-71bce95fc3ad)

VISA after:
![image](https://github.com/ni/measurementlink-labview/assets/17914399/8ea5c877-829e-45a0-bbe1-2072cec5f8fd)
![image](https://github.com/ni/measurementlink-labview/assets/17914399/86e37a2d-eb75-4b7e-a15d-511cd886281d)

## Context

Testing

## Your Environment

* OS & Device: Windows 10
* `ni-measurement-service` version: users/jay/update-example-sequences
* MeasurementLink version: 24.0.0d499
* LabVIEW version: LabVIEW 2021 SP1

[AB#2601905](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2601905)

**Comment by jasonmreding** [comment]
This is fixed by #463 .
