### ISSUE TITLE
Throw more descriptive error for wrong data types

### ISSUE THREAD

**Issue by pbirkhol-ni** [ni/measurementlink-labview#478]
# Bug Report

Throw a more descriptive error message when an input/output is an unsupported type. Currently we mention what inputs and outputs have an unsupported type, but it would be clearer if we added information. For example, may be we mention the current data type and the list the supported data types.

[AB#2633808](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2633808)

**Comment by dixonjoel** [comment]
#479
