### ISSUE TITLE
Document format/content of information provided by `Get Measurement Details` 

### ISSUE THREAD

**Issue by bkeryan** [ni/measurementlink-labview#60]
The readme says

> 3. Add the measurement details in the block diagram of the Get Measurement Details.vi including:
> 
> display name
>version
>measurement type
>product type
>service id
><img src="https://github.com/ni/measurement-services-labview/raw/main/docs/images/Get%20Measurement%20Details%20VI.png">

What format should measurement type, product type, and service id be in?

Is service id still a GUID, or has that changed?

If service id is a GUID, should it include curly braces? https://github.com/ni/measurement-services-labview/issues/31 shows that various projects are inconsistent about this.

If service is a GUID and it includes curly braces, the string constant in the template needs to be bigger:
![image](https://user-images.githubusercontent.com/17914399/174681875-9d9a957d-bc65-43d0-ad9a-5c8f25b5b169.png)

How should the developer generate a GUID? I used `guidgen.exe`, which is included with Visual Studio, but many LabVIEW developers will not have this tool installed.

[AB#2270641](https://dev.azure.com/ni/DevCentral/_workitems/edit/2270641)
Link added manually by dixonjoel

**Comment by dixonjoel** [comment]
@rfriedma @bkeryan 
Here's the latest screenshot. Is this sufficiently clear or any changes we want to make?
![image](https://user-images.githubusercontent.com/38357562/217917635-a22cd0b5-aa3d-4306-a288-4eedeb91da97.png)

**Comment by rfriedma** [comment]
I'd show labels for all constant fields like the original above

**Comment by dixonjoel** [comment]
@aepete would you be able to make this small change while you're updating to grpc-labview 1.0.0.1?

**Comment by dixonjoel** [comment]
Updated Get Measurement Details.vi in #177
