### ISSUE TITLE
`Run Service.vi` does not chain registration errors properly 

### ISSUE THREAD

**Issue by bkeryan** [ni/measurementlink-labview#99]
When `Run Service.vi` fails to register with the discovery service, it doesn't display an error until you click the `STOP` button.

[AB#2270486](https://dev.azure.com/ni/DevCentral/_workitems/edit/2270486)
Link added manually by dixonjoel

**Comment by aepete** [comment]
In addition to errors encountered during registration with Discovery Service, `Run Service.vi` also mishandles cases like the user reporting an error in a fundamental plugin VI such as `Get Measurement Details.vi`.  We should make effort to address all these types of errors holistically and robustly.
